### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by jboolean** [ChromeAdmin/meetings-page-auto-closer-for-zoom#14]
Not seeing any effect, including on the zoom.us/test meeting.

**Comment by ChromeAdmin** [comment]
hi @jboolean  , when visiting the zoom.us/test link and joining a test meeting, you are redirected to a url that looks like this
`
https://zoom.us/j/96978517402?pwd=cTlYNlJ5Z1BmclZtYy9ZMnpqcnNRdz09#success
`
and in the Chrome Dev Console, when the extension is loaded, it console.logs look like this:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/64453142/210473778-8f5c570b-3464-4b3b-b278-9dc08766fc80.png">
Do you see any of this in your Chrome Dev Console too?

**Comment by ChromeAdmin** [comment]
closing because no response.
