### ISSUE TITLE
Close in 1 second option

### ISSUE THREAD

**Issue by airbornelamb** [ChromeAdmin/meetings-page-auto-closer-for-zoom#15]
Would echo some of the feedback in the reviews of the chrome extension. It would be great to have a "close in 1 second" option instead of the minimum of 5 seconds.

**Comment by ChromeAdmin** [comment]
Hi, as I've answered in previously closed "issues". Any chrome extension, including this one, does not know if an external application was successfully launched... such as Zoom. If the tab is closed too quickly then Zoom will not launch.

Therefore, if the extension were to close to tab after 1 second... your Zoom meeting will very likely never be launched.
