### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by robmonte** [ChromeAdmin/meetings-page-auto-closer-for-zoom#9]
Are you able to package this for Firefox as well? I prefer your version of this extension but it's unfortunate that it's locked to Chrome.

**Comment by ChromeAdmin** [comment]
Thanks! I'll look into what it would take to make this available for Firefox too.

**Comment by forivall** [comment]
I use https://github.com/grrttedwards/zoom-tab-closer on firefox, you can probably look at their manifest, etc to get some info on how to make this available in AMO (addons.mozilla.org)

**Comment by ChromeAdmin** [comment]
Made a branch for the Firefox version and prepped it for submission.

We are waiting for Google to re-approve the extension and then submit in Firefox.

( see [Extension suspended by Google due to Zoom name Trademark infringement](https://github.com/ChromeAdmin/meetings-page-auto-closer-for-zoom/issues/10)  )

Stay tuned!

**Comment by pkmnct** [comment]
@ChromeAdmin Did you ever revisit publishing the Firefox version?

**Comment by ChromeAdmin** [comment]
@pkmnct , it's waiting to be listed.
https://addons.mozilla.org/en-US/firefox/addon/meetings-page-auto-closer-zoom/
<img width="512" alt="image" src="https://user-images.githubusercontent.com/64453142/175699334-25029f3a-d91a-4fed-a078-109979cf4bb6.png">

**Comment by danielnaber** [comment]
It's now available at https://addons.mozilla.org/en-US/firefox/addon/meetings-page-auto-closer-zoom/ and it works for me, thanks!

**Comment by robmonte** [comment]
Closing the issue since it has been live for a bit now. Thanks for providing this @ChromeAdmin !
